### ISSUE TITLE
Banner image on homepage UI 

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Shony-Ships-Store-redesign#1]
Bug - banner image getting blur on homepage.
Exp - 
- banner images should be clear.
- banner text should be capitalised.
Exp Ref - https://drive.google.com/file/d/18BW8gLeFSZ8UugDKqapEcoQlZpU5B2ft/view

**Comment by ui-manjeshyadav** [comment]
Image not yet provided by the graphic designer

**Comment by ankitcedcoss** [comment]
Bug Fixed
