### ISSUE TITLE
Privacy policy page UI issue - Mobile UI

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Shony-Ships-Store-redesign#10]
Bug - Privacy policy page shaking and content trimming on page UI issue on mobile UI.
Exp - Page should be stable and text not get trim on page.
Ref Link - https://drive.google.com/file/d/1F7D2Zpq8Vw9BKi0co4Z0QdPzfJ2ZGwRg/view

**Comment by ui-manjeshyadav** [comment]
right then it is showing in my laptop

**Comment by ankitcedcoss** [comment]
Bug Not Fixed - Please check the video.
- https://drive.google.com/file/d/18gj1R8AYJMr0Q7eq-pUCpC4Xk_TM9cKl/view

**Comment by ankitcedcoss** [comment]
Bug Fixed
