### ISSUE TITLE
Validation issue on account page fields.

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Shony-Ships-Store-redesign#13]
Bug - Validation error not showing on blank field and invalid email.
Exp - Add validation message on account page fields.
Login.
Create account.
Recover Password.
Ref  Link - https://drive.google.com/file/d/1h57QyNH1fenT-HbXRVvYydj6tGss2195/view

**Comment by dev-adityapatel** [comment]
@ankitcedcoss  we follow only following point, no any additional work done

These are the following changes you need to make in the store : 
1. Policy Pages
- Privacy Policy
- Billing Terms and Conditions
- Secure Checkout Page
- FAQs
- Shipping Policy (need to add more details)
- Terms of Services (need to change contents)
- Return and Refund Policy (need to add more details, like days, state of return, the reason for return, process of return and refund, contact details, etc.)

2. Other Pages
- Contact Us (Show Contact Address, Email, and phone number, support available time, contact us form)
- About Us page (Show company details, aims, and objectives, why should a customer choose you, year of establishment, and email)

3. Product landing page : 
- Do not copy contents like product images, titles, or descriptions exact from any source
- Show your name as Brand name

4. Make sure the check-out process is secure and safe
- Show all the payment methods shown in the footer while check-out
- Make sure the shipping charges and taxes are the same as mentioned on the policy pages

**Comment by ankitcedcoss** [comment]
Closing on Not Required
