### ISSUE TITLE
banner text hiding in responsive  - Mobile UI

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Shony-Ships-Store-redesign#2]
Bug - Banner text hidinge behing navigation buttons on homepage.
Exp - Banner text should not hide in responsive.
Ref Link - https://nimb.ws/h3piRM

**Comment by ui-manjeshyadav** [comment]
Content writer has not yet provided the content

**Comment by ankitcedcoss** [comment]
Bug Fixed
