### ISSUE TITLE
Back to login button not available on create account page

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Shony-Ships-Store-redesign#20]
Bug - Back to login button not available on create account page.
Exp - Add back to login button on create account page.
Ref Link - https://nimb.ws/4K6Jyi

**Comment by dev-adityapatel** [comment]
@ankitcedcoss  Issue resolved

![image](https://user-images.githubusercontent.com/100192519/164878048-0d15d405-55c9-4de0-a256-71c2f184ef3f.png)

**Comment by ankitcedcoss** [comment]
Bug Fixed
