### ISSUE TITLE
Banner images trimming on responsive - tab and mobile

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Shony-Ships-Store-redesign#4]
Bug - banner image trimming on homepage - mobile and tab
Exp - image should not get trim on mobile and tab
Ref Link - https://drive.google.com/file/d/1tmROjepGy8HsDUACoD_U3ks_FHVnvE9b/view

**Comment by ui-manjeshyadav** [comment]
Image not yet provided by the graphic designer

**Comment by ankitcedcoss** [comment]
Bug Fixed
