### ISSUE TITLE
Collections page spacing and tile UI issue

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Shony-Ships-Store-redesign#6]
Bug - Not spacing showing between footer and tile UI button and showing less spacing on grid.
Exp - 
- Add spacing between footer and tile button.
- Add spacings on grid on collection page.
Ref Link - https://drive.google.com/file/d/1qkU9ncGF4qTwrihoQpZ4dUaWBlWXf_fB/view

**Comment by ui-manjeshyadav** [comment]
Which two collection is coming in one row is right

**Comment by ankitcedcoss** [comment]
Bug Not Fixed
![image](https://user-images.githubusercontent.com/100753159/164888889-e4beb96a-e161-40b7-8e00-40745a744973.png)

**Comment by ankitcedcoss** [comment]
Bug Fixed
